# Generated by Django 6.0.2 on 2026-03-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_specialist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('ile-de-france', 'Île-de-France'), ('auvergne-rhone-alpes', 'Auvergne-Rhône-Alpes'), ('nouvelle-aquitaine', 'Nouvelle-Aquitaine'), ('occitanie', 'Occitanie'), ('hauts-de-france', 'Hauts-de-France'), ('provence-alpes-cote-azur', "Provence-Alpes-Côte d'Azur"), ('grand-est', 'Grand Est'), ('pays-de-la-loire', 'Pays de la Loire'), ('normandie', 'Normandie'), ('bretagne', 'Bretagne'), ('bourgogne-franche-comte', 'Bourgogne-Franche-Comté'), ('centre-val-de-loire', 'Centre-Val de Loire')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Clinique',
                'verbose_name_plural': 'Cliniques',
                'ordering': ['region', 'city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.clinic'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='clinics',
            field=models.ManyToManyField(blank=True, to='appointments.clinic'),
        ),
    ]
